#page title
page_title                                : AR Frames                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234567                             # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : #https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/splash_glasses.jpg                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : AR Frames                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : NSA AR Frames for Infor Hackathon.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : NSA Professional Services                              
your_link                                 : https://theblackapple5150.github.io/Frames/                     
your_city                                 : New York                                
email_address                             : support@nsacom.com
facebook_username                         :                                           
instagram_username                        : #ebaehr
twitter_username                          : #ebaehr
github_username                           : NSA-Computer-Exchange
youtube_username                          :
mastodon_link                             : #https://mastodon.social/@ebaehr



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : NSA Professional Services
    description                           : Imagined and Designed by NSA Professional Services.
    fontawesome_icon_name                 : handshake
    
  - title                                 : iPhone Powered / Bluetooth Enabled
    description                           : Powered by iPhone over BTLE
    fontawesome_icon_name                 : mobile

  - title                                 : Augmented Reality Glasses 
    description                           : AR Glasses created by by <a href="https://brilliant.xyz/">Brilliant Labs.xyz</a>
    fontawesome_icon_name                 : glasses

  - title                                 : Hands-Free / Voice Enabled
    description                           : Hands-Free operation. Get product information or add ICSP/ICSW product images by looking at a product. Navigate the app and dictate the product code.
    fontawesome_icon_name                 : microphone

  - title                                 : Easy to Use
    description                           : Intuitive controls and easily access the help menu at any time. See available commands on the glasses.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Feature List
    description                           : <p><li>Add Product Images to CSD</li></p>
                                            <p><li>Get Product Details</li></p>
                                            <p><li>See Current Battery Level</li></p>
                                            <p><li>See Date & Time</li></p>
                                            <p><li>Get Current Firmware Level</li></p>
                                            <p><li>Show/Hide Event Logs</li></p>
                                            <p><li>Emulate AR View on Phone</li></p> 
    fontawesome_icon_name                 : star

  - title                                 : Frame App SDK
    description                           : <p><li>Python Mac, Linux or Windows</li></p>
                                            <p><li>Swift from a Mac or iOS device</li></p>
                                            <p><li>Kotlin from Android</li></p>
                                            <p><li>Flutter for mobile</li></p>
                                            <p><li>React Native for mobile</li></p>
    fontawesome_icon_name                 : code

  - title                                 : Social Links
    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : link

  - title                                 : FontAwesome Support
    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
